### ISSUE TITLE
ModuleNotFoundError: No module named 'df_apply'

### ISSUE THREAD

**Issue by jolespin** [kylessmith/dynamicTreeCut#7]
```
$ pip install dynamicTreeCut
Collecting dynamicTreeCut
  Downloading https://files.pythonhosted.org/packages/61/98/906accd73cf0efca220f4bf219533f3edf2ff6b83b90da99173cdaec5d74/dynamicTreeCut-0.1.0.tar.gz
Requirement already satisfied: numpy in ./anaconda/envs/python3/lib/python3.6/site-packages (from dynamicTreeCut) (1.13.3)
Requirement already satisfied: scipy in ./anaconda/envs/python3/lib/python3.6/site-packages (from dynamicTreeCut) (1.1.0)
Building wheels for collected packages: dynamicTreeCut
  Running setup.py bdist_wheel for dynamicTreeCut ... done
  Stored in directory: /Users/mu/Library/Caches/pip/wheels/6a/a6/84/caf6657f91fb0f752c27c64efbf4508165705e23e458367a20
Successfully built dynamicTreeCut
Installing collected packages: dynamicTreeCut
Successfully installed dynamicTreeCut-0.1.0
(python3) Joshs-MacBook-Pro:~ mu$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynamicTreeCut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mu/anaconda/envs/python3/lib/python3.6/site-packages/dynamicTreeCut/__init__.py", line 8, in <module>
    from .dynamicTreeCut import cutreeHybrid
  File "/Users/mu/anaconda/envs/python3/lib/python3.6/site-packages/dynamicTreeCut/dynamicTreeCut.py", line 5, in <module>
    import df_apply
ModuleNotFoundError: No module named 'df_apply'
>>>
```

**Comment by jolespin** [comment]
It looks like the error is gone now.  Should I close this issue?

**Comment by duncster94** [comment]
I'm having this issue as well.

EDIT: This can be fixed by replacing `import df_apply` with `import dynamicTreeCut.dy_apply`. Also replace `from R_func import *` with `from dynamicTreeCut.R_func import *`.

**Comment by jolespin** [comment]
Try installing straight from the github like this:

pip install git+https://github.com/kylessmith/dynamicTreeCut

**Comment by kylessmith** [comment]
I pushed the most recent github updates to pypi. Let me know if you are still having this issue
